apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
     app: kubiarc
spec:
  containers:
  - image: stv707/kubia-unhealthy:v1
    name: kubia
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      periodSeconds: 5
    ports:
    - containerPort: 8080
      protocol: TCP