apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
  labels:
     app: kubiarc
spec:
  containers:
  - image: stv707/kubia-unhealthy:v1
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP