apiVersion: v1
kind: Pod
metadata:
  name: box1
  labels:
    app: box1
spec:
  containers:
  - name: box1
    image: stv707/multitool:v1
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80
    command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]