apiVersion: v1
kind: Pod
metadata:
  name: kubia-pod
  labels: 
    app: kubia-pod
spec:
  containers:
  - image: stv707/kubia:v14
    name: kubia-pod
    ports:
    - containerPort: 8080
      protocol: TCP