apiVersion: v1
kind: Pod
metadata:
  name: seccon3
spec:
  volumes:
  - name: security-context-vol
    emptyDir: {}
  containers:
  - name: security-context-cont
    image: stv707/capsh:v2
    command: ["/bin/sleep", "999999"]
    volumeMounts:
    - name: security-context-vol
      mountPath: /data/test
    securityContext:
      capabilities:
        drop: 
          - ALL